services:
  db:
    image: postgres:16.4-alpine
    networks:
      - db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - envs/db.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d postgres" ]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 3s
      start_interval: 1s
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    env_file:
      - envs/db.env
      - envs/app.env
    command: |
      /usr/bin/env sh -c "gunicorn -k gevent config.wsgi --bind=0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
networks:
  db:
    driver: bridge
volumes:
  pgdata:
    name: task_app_db
    driver: local
    