# Generated by Django 5.1.1 on 2024-09-12 10:04

import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=model_utils.fields.StatusField(choices=[('to_do', 'To do'), ('done', 'Done')], default='to_do', max_length=100, no_check_for_status=True, verbose_name='Status'),
        ),
    ]
