# Generated by Django 5.1.1 on 2024-09-12 10:07

from django.db import migrations


IS_DONE_TO_STATUS_MAP = {
    True: 'done',
    False: 'to_do',
}
STATUS_TO_IS_DONE_MAP = {v: k for k, v in IS_DONE_TO_STATUS_MAP.items()}


def migrate_task_is_done_to_status(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    for task in Task.objects.all():
        task.status = IS_DONE_TO_STATUS_MAP.get(task.is_done, task.status)
        task.save()


def migrate_task_status_to_is_done(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    for task in Task.objects.all():
        task.is_done = STATUS_TO_IS_DONE_MAP.get(task.status, task.is_done)
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_task_status'),
    ]

    operations = [
        migrations.RunPython(migrate_task_is_done_to_status, migrate_task_status_to_is_done),
    ]
